0
SLURM_JOBID=6482
SLURM_JOB_NODELIST=iitrdgx
SLURM_NNODES=1
SLURMTMPDIR=
Date              = Wed Sep  8 00:55:56 IST 2021
Hostname          = iitrdgx

Number of Nodes Allucated      = 1
Number of Tasks Allocated      = 1
Number of Cores/Task Allocated = 4
Working Directory = /raid/ysharma_me/fair_lr/lff_vanilla
working directory = /raid/ysharma_me/fair_lr/lff_vanilla
/raid/ysharma_me/fair_lr/lff_vanilla
iitrdgx
Wed Sep  8 00:55:56 IST 2021
0

=============
== PyTorch ==
=============

NVIDIA Release 20.11 (build 17345815)
PyTorch Version 1.8.0a0+17f8c32

Container image Copyright (c) 2020, NVIDIA CORPORATION.  All rights reserved.

Copyright (c) 2014-2020 Facebook Inc.
Copyright (c) 2011-2014 Idiap Research Institute (Ronan Collobert)
Copyright (c) 2012-2014 Deepmind Technologies    (Koray Kavukcuoglu)
Copyright (c) 2011-2012 NEC Laboratories America (Koray Kavukcuoglu)
Copyright (c) 2011-2013 NYU                      (Clement Farabet)
Copyright (c) 2006-2010 NEC Laboratories America (Ronan Collobert, Leon Bottou, Iain Melvin, Jason Weston)
Copyright (c) 2006      Idiap Research Institute (Samy Bengio)
Copyright (c) 2001-2004 Idiap Research Institute (Ronan Collobert, Samy Bengio, Johnny Mariethoz)
Copyright (c) 2015      Google Inc.
Copyright (c) 2015      Yangqing Jia
Copyright (c) 2013-2016 The Caffe contributors
All rights reserved.

NVIDIA Deep Learning Profiler (dlprof) Copyright (c) 2020, NVIDIA CORPORATION.  All rights reserved.

Various files include modifications (c) NVIDIA CORPORATION.  All rights reserved.
NVIDIA modifications are covered by the license terms that apply to the underlying project or file.

NOTE: Legacy NVIDIA Driver detected.  Compatibility mode ENABLED.

ERROR: Detected MOFED driver 4.0-1.0.1, but this container has version 5.1-2.3.7.
       Please upgrade to MOFED 4.9 or higher for multi-node operation support.

[19:26:02] [WARNING] [debias.main] No observers have been added to this run
[19:26:02] [INFO] [debias.main] Running command 'train'
[19:26:02] [INFO] [debias.main] Started
CelebA
[19:26:02] [ERROR] [debias.main] Failed after 0:00:00!
Traceback (most recent calls WITHOUT Sacred internals):
  File "/raid/ysharma_me/fair_lr/lff_vanilla/train.py", line 54, in train
    transform_split="train",
  File "/raid/ysharma_me/fair_lr/lff_vanilla/data/util.py", line 120, in get_dataset
    transform=transform,
  File "/opt/conda/lib/python3.6/site-packages/torchvision/datasets/celeba.py", line 84, in __init__
    ' You can use download=True to download it')
RuntimeError: Dataset not found or corrupted. You can use download=True to download it

